### ISSUE TITLE
ロボット間の通信方式を確認する

### ISSUE THREAD

**Issue by yasuohayashibara** [citbrains/GankenKun_webots#30]
ロボット間での通信方式が不明であるので調べる．
とりあえずは今の仕組みで通信しても良いと思うが，DARwIn-OPのprotoファイルに通信の設定も入っていたため，もしかしたらwebotsを介して通信をしなければならないかもしれない．

**Comment by KANBE8810** [comment]
ルールを確認したところ、通信に関しては今までの世界大会とルールが変わっていないそうなので、むしろEmitterとReceiverで通信するほうがルール違反かもしれません。
ですので、今の仕組みで通信すればいいと思います。

**Comment by yasuohayashibara** [comment]
解決したので，issueを閉じます．
