### ISSUE TITLE
白線検出の重み作成

### ISSUE THREAD

**Issue by RikuYokoo** [citbrains/GankenKun_webots#33]

**Comment by RikuYokoo** [comment]
webots用の白線検出用の重みを作成した。
はじめはテストとして12枚の画像で作成した。
[使用画像](https://drive.google.com/drive/folders/1w1o2QJPeOZUJ2cYQWI5WOPePsOpfdPof)。
作成重み[model_20210430_154400.npz](https://drive.google.com/drive/folders/1bR-v9qMcUN5rC6BO5ywkYL5bSy0XrlGb)

**Comment by yasuohayashibara** [comment]
大会用の環境でチェックしたときの様子です．
https://youtu.be/g1VbOPy8fsk

ボールとロボットの足にご認識がありますが，とりあえず問題無いと思います．
実環境で使用していた重み(wl_2layer_20190622_142021.npz)と比較しましたが，明らかに良くなっています．

**Comment by yasuohayashibara** [comment]
利用法を記載して，issueを閉じてください．
認識が不十分な場合は再度オープンしましょう．

**Comment by RikuYokoo** [comment]
[こちら](https://github.com/citbrains/citbrains_humanoid/wiki/Jetson%E3%81%AE%E7%92%B0%E5%A2%83%E6%A7%8B%E7%AF%89)に記述しましたのでissueを閉じたいと思います.
