### ISSUE TITLE
TC検証(05/23)までにDockerイメージの作成

### ISSUE THREAD

**Issue by KANBE8810** [citbrains/GankenKun_webots#34]
Dockerイメージを5月23日までに4機体分を作成して提出する。
提出するTC検証用のDockerイメージは、技術委員会がリアルタイムファクタで、大会で使用されるハードウェア上でシュミレーションできる必要がある。

**Comment by yasuohayashibara** [comment]
作成するDockerは以下の形で間違い有りませんでしょうか？
https://github.com/citbrains/GankenKun_webots/issues/28#issuecomment-828860729

**Comment by KANBE8810** [comment]
おそらく間違いないとは思いますが、10日にAPIとかの仕様書の更新があるので、そちらの方で改めて確認したいと思います。

**Comment by KANBE8810** [comment]
検証用のDockerfleが完成してimage buildとdocker runも通りました。
これからwebotsとの通信がうまくいくかどうかを確かめたいと思います。

Dockerfileには問題がなかったのですが、作成したimageが5.11GBとルールの5GBを超えてしまっているので対策が必要です(darknetとかもいれようとすると更にシビアになるかもしれません)
現状ではcitbrains_humanoidからcloneするものを減らすという形で対応したいと考えています。

**Comment by yasuohayashibara** [comment]
dockerの仕組みを十分に理解していないのですが，実際の試合で提供するのはバイナリになると思いますので，ソースコードやgithubにある過去の履歴などは削除したdockerで検証して良いと思います．
dockerの中で開発するのであれば，ソースコードも含めた方が良いかもしれませんが．

**Comment by kiyoshiiriemon** [comment]
ソースや中間オブジェクトは消すのがよいと思います。
またgit clone --depth=1 でクローンすれば最新の履歴だけ取得できるのでサイズを減らすことができます。

**Comment by KANBE8810** [comment]
入江さんのコマンドを使用したところ5.11GBから4.57GBまで減らすことができました。
画像1枚目が普通にcloneしてmakeしたとき、
画像2枚目が入江さんのコマンドでcloneしてmakeしたときのdfの結果です。
Availableの値が大きく変わっていますが、これは僕の端末内の不要なimagesを削除しただけなので気にしないでください。

![Screenshot from 2021-05-14 13-38-59](https://user-images.githubusercontent.com/50877609/118224841-e1340200-b4be-11eb-8e0e-72800c0acb37.png)
![Screenshot from 2021-05-14 14-15-07](https://user-images.githubusercontent.com/50877609/118224846-e3965c00-b4be-11eb-81dc-932a304e65c1.png)

**Comment by KANBE8810** [comment]
調べていたらマルチステージビルドをするとコンテナイメージを大幅に抑えられる可能性があるという記事を見つけたので、次はそちらを試してみたと思います。

**Comment by KANBE8810** [comment]
runstrategy.pyの起動まで確認して、srcのmakeまで自動でやるようにdockerfileを書きました。

**Comment by KANBE8810** [comment]
### 23日までにやること
- [ ] 歩行用コードの開発

- [ ] IPアドレスなどの設定

- [ ] リアルタイムでシュミレーションできるかを確認

### 6月の模擬試合までにやること
- [ ] YOLOに対応させる(NVIDIAとかをインストール)

上から順々にやっていこうと思います。
他に23日までにDocker関連でやらなければならないことがあれば指摘してください。

**Comment by KANBE8810** [comment]
とりあえずその場歩きを永遠と行うコードを書いて、develop/RobVup2021で動作確認を行ったところ、問題なく歩行を1分以上続けられていました。
https://github.com/citbrains/citbrains_humanoid/blob/develop/RoboCup2021/for2050/src/pyfiles/endless_walk.py

**Comment by yasuohayashibara** [comment]
入江さんのブランチが最終的に提出するプログラムとなると思いますので，そちらで検証していただければと思います．
（先ほどprotoモデルをアップデートしたので，関節の回転が逆方向になるかもしれません．）

**Comment by yasuohayashibara** [comment]
本日(05/22)，本番の環境を用意しますので，そちらでチェックしましょう．
そういえばwebotsサーバの計算結果を表示する方法が分からないままですが．．．

**Comment by KANBE8810** [comment]
複数コマンドを実行させなきゃいけないことを完全に忘れてました。
現状としてはdocker-composeでそれぞれを実行するコンテナを作成してコンテナ間通信で戦略を動かそうかと考えています。
何かもっと良い方法があれば教えていただきたいです。 @kiyoshiiriemon

**Comment by KANBE8810** [comment]
解決しました。

**Comment by yasuohayashibara** [comment]
フランクフルトのサーバーでwebotsの起動を確認しました．
まだポートを開けていないので，これから開けます．
必要な設定がありましたら，行いますのでよろしくおねがいします．

user: ubuntu
password: ubuntu
アドレス　3.122.251.119
（フランクフルトなので遅いです）

![image](https://user-images.githubusercontent.com/5755200/119214794-78730800-bb04-11eb-9e07-7fc0aa8c541f.png)

**Comment by yasuohayashibara** [comment]
ポートを開けて以下のメッセージが戻ってくることを確認しました．

- webotsサーバを起動していない場合
```
mirai@mirai-virtual-machine:~/robocup/for2050/src/webots$ ./WebotsClient
Cannot connect to 3.122.251.119:10021
Connection closed by server.
```
- webotsサーバを起動した場合
```
mirai@mirai-virtual-machine:~/robocup/for2050/src/webots$ ./WebotsClient
Connection to 3.122.251.119:10021 refused: your IP address is not allowed in the game.json configuration file.
TIME=0
```

**Comment by yasuohayashibara** [comment]
終了しましたのでissueを閉じます．
