### ISSUE TITLE
GankenKun_walkingの実行環境

### ISSUE THREAD

**Issue by yasuohayashibara** [citbrains/GankenKun_webots#56]
確認済みの動作環境

Ubuntu1804
python 3.6.9
control 0.8.4
webots R2021b
https://github.com/cyberbotics/webots/releases/tag/R2021b

**Comment by yasuohayashibara** [comment]
@MibuchiYuta 
参考までに確認済みの動作環境をお伝えします．

**Comment by MibuchiYuta** [comment]
ありがとうございます。以下の環境で私も起動を確認しました。

- Ubuntu 20.04
- Anaconda3
  - python 3.6.10
  - control-0.9.0 
  - transforms3d-0.3.1 
  - scikit-optimize-0.9.0
- webots R2021b

**Comment by yasuohayashibara** [comment]
解決したためissueを閉じます．
