### ISSUE TITLE
collect_images.wbtを動かしていると途中でバスエラーが出る

### ISSUE THREAD

**Issue by RyokoShiojima** [citbrains/GankenKun_webots#65]
動かしてからしばらくすると下の図のようなエラーが出てwebotsが落ちます。

![Screenshot from 2022-04-27 14-41-08](https://user-images.githubusercontent.com/40712113/165449954-16a24d6c-2680-42c9-8246-8e02979a3e5f.png)

**Comment by yasuohayashibara** [comment]
画像収集のプログラムですが，大量に画像を取得してもエラーが発生しないように作り変えました．
従来はロボットを一旦削除して生成してたのですが，削除せずにロボットを移動させるようにしました．
ちなみに，Webots上で瞬間的に移動させると徐々にロボットがバラバラになるという現象が見られたので，従来のプログラムでは避けていました．
シミュレーションを定期的にリセットすることでばらばらになる現象を回避できることが分かりましたので，定期的にリセットを入れています．
（そのタイミングで視点も戻されます．）

コミット番号
ed7f49b7f668b7486722d225be5f7a868f37c110

**Comment by yasuohayashibara** [comment]
解決しましたのでissueを閉じます．
